texts = {
    'uz': {
        'buttons': [
            ["📐 Rasmni bo‘lish", "🖤 Oq-qora qilish"],
            ["✂️ Rasmni kesish", "🌐 Tilni o‘zgartirish"],
            ["💡 taklif", "🆘 yordam"]
        ],
        'start': "👋 Salom! Men rasm tahriri botiman. Quyidagilardan birini tanlang:",
        'help': "🛠 Yordam:\n/start — boshlash\n/help — yordam\n/about — bot haqida\n/contact — bog‘lanish\n/taklif — taklif yuborish",
        'about': "🤖 Bu bot rasmni bo‘lish, oq-qora qilish, kesish va tilni almashtirish imkonini beradi.",
        'contact': "📬 Bog‘lanish uchun: @SherzodDew",
        'send_photo': "📸 Iltimos, avval rasm yuboring.",
        'image_saved': "✅ Rasm saqlandi! Endi amallarni bajaring.",
        'enter_split': "📐 Nechta bo‘lakka bo‘laylik? Masalan: 4 yoki 2x2",
        'wrong_format': "❌ Format noto‘g‘ri! Masalan: 6 yoki 2x3",
        'only_nums': "⚠️ Faqat 2, 4, 6, 8, 9 yoki 10 sonlari qabul qilinadi.",
        'split_done': "✅ Bo‘lish yakunlandi: {rows}x{cols} = {total} bo‘lak",
        'grayscale_done': "✅ Oq-qora rasm tayyor!",
        'enter_crop_size': "✂️ Rasm o‘lchami: {width}×{height}. Qanday o‘lchamda kesaylik? (masalan: 600x400)",
        'crop_too_big': "⚠️ Kiritilgan o‘lcham rasmdan katta bo‘lmasin.",
        'crop_done': "✅ Rasm kesildi: {w}x{h}",
        'lang_set': "✅ Til o‘zgartirildi.",
        'unknown': "❓ Noma'lum buyruq. Yordam kerak bo‘lsa /help ni bosing.",
        'send_suggestion': "✍️ Taklifingizni yozing. Admin unga ko‘z tashlaydi.",
        'suggestion_thanks': "✅ Taklif uchun rahmat!",
    },
    'ru': {
        'buttons': [
            ["📐 Разделить изображение", "🖤 Чёрно-белое"],
            ["✂️ Обрезать изображение", "🌐 Сменить язык"],
            ["💡 предложение", "🆘 помощь"]
        ],
        'start': "👋 Привет! Я бот для обработки изображений. Выберите действие:",
        'help': "🛠 Помощь:\n/start — начать\n/help — помощь\n/about — о боте\n/contact — контакт\n/taklif — отправить предложение",
        'about': "🤖 Этот бот может разделять, обрезать, делать ч/б и менять язык.",
        'contact': "📬 Связь: @SherzodDew",
        'send_photo': "📸 Пожалуйста, сначала отправьте изображение.",
        'image_saved': "✅ Изображение сохранено! Выберите действие.",
        'enter_split': "📐 На сколько частей разделить? Например: 4 или 2x2",
        'wrong_format': "❌ Неверный формат! Например: 6 или 2x3",
        'only_nums': "⚠️ Только числа: 2, 4, 6, 8, 9, 10.",
        'split_done': "✅ Разделено: {rows}x{cols} = {total} частей",
        'grayscale_done': "✅ Черно-белое изображение готово!",
        'enter_crop_size': "✂️ Размер изображения: {width}×{height}. Какой размер вырезать? (например: 600x400)",
        'crop_too_big': "⚠️ Размер больше изображения!",
        'crop_done': "✅ Обрезано до: {w}x{h}",
        'lang_set': "✅ Язык изменён.",
        'unknown': "❓ Неизвестная команда. Нажмите /help для справки.",
        'send_suggestion': "✍️ Напишите ваше предложение. Я передам администратору.",
        'suggestion_thanks': "✅ Спасибо за предложение!",
    },
    'en': {
        'buttons': [
            ["📐 Split Image", "🖤 Grayscale"],
            ["✂️ Crop Image", "🌐 Change Language"],
            ["💡 offer", "🆘 help"]
        ],
        'start': "👋 Hi! I'm an image editing bot. Choose one below:",
        'help': "🛠 Help:\n/start — start\n/help — help\n/about — about\n/contact — contact\n/taklif — send suggestion",
        'about': "🤖 This bot can split, crop, grayscale images and change language.",
        'contact': "📬 Contact: @SherzodDew",
        'send_photo': "📸 Please send a photo first.",
        'image_saved': "✅ Image saved! Ready for editing.",
        'enter_split': "📐 Into how many parts? For example: 4 or 2x2",
        'wrong_format': "❌ Wrong format! Try: 6 or 2x3",
        'only_nums': "⚠️ Only 2, 4, 6, 8, 9, or 10 allowed.",
        'split_done': "✅ Split done: {rows}x{cols} = {total} pieces",
        'grayscale_done': "✅ Grayscale image ready!",
        'enter_crop_size': "✂️ Image size: {width}×{height}. Crop to what size? (e.g., 600x400)",
        'crop_too_big': "⚠️ Size too big for image!",
        'crop_done': "✅ Cropped to: {w}x{h}",
        'lang_set': "✅ Language changed.",
        'unknown': "❓ Unknown command. Use /help if needed.",
        'send_suggestion': "✍️ Type your suggestion. I’ll send it to admin.",
        'suggestion_thanks': "✅ Thanks for your suggestion!",
    }
}
